### ISSUE TITLE
DecimalMaxAttribute\DecimalMinAttribute should be culture invariant when defines CheckConstraint string

### ISSUE THREAD

**Issue by pasqualedante** [darioquintana/NHibernate-Validator#1]
When local culture use comma as decimal separator, the statement
col.CheckConstraint = col.Name + "<=" + Value;
invoke silently Value.ToString that return comma as decimal separator.
For example, in my case, I'm italian and setting 0.01 as decimal min I have a constraint
as check (column_name>= 0,01) that is a bad Sql statement. 

This issue is already reported by me to jira bugs tracker (where NHV seems to be abandoned)

**Comment by darioquintana** [comment]
Pasquale thanks for contributing!

**Comment by pasqualedante** [comment]
My mistake: I have created twice the same bug (this is a dupe of bug #2). I'm sorry ;-) 

=> Closed as dupe
